### ISSUE TITLE
サーフェイスがHDRになっていない

### ISSUE THREAD

**Issue by comoc** [xperiavr/android-native-egl-example#1]
@kamiya-m さんからSlackに頂いたバグレポ
https://unity.slack.com/archives/C01G4B6ELHF/p1610671013009400?thread_ts=1610636127.008600&cid=C01G4B6ELHF

> まずは動かしてみましたが、10bitのSurfaceは生成されているもののColor ModeはP3でHDRになっているレイヤーは存在しませんでした。これは意図通りではないですよね？
> ちなみに私が使用している端末は203でも215でもなく204です。手元にあるのが204とXperia1だけなのですがまずいでしょうか？
> renderer.cppで使っているEGL_COLORSPACEをEGL_GL_COLORSPACE_KHRに変更したらHDRになりましたが、この修正で良いですか？

**Comment by kamiya-m** [comment]
#1 を動作させて問題ないことを確認しました。 @comoc

**Comment by comoc** [comment]
クローズします。
